-- CREATING A FUNCTION

CREATE OR REPLACE FUNCTION FUNC_RETDEPT (P_ID IN NUMBER)

RETURN VARCHAR2

IS 

V_RETORN DEPARTMENTS.DEPARTMENT_NAME%TYPE;

BEGIN

  IF P_ID > 0 AND P_ID < 999999 THEN
    
    SELECT DEPARTMENT_NAME INTO V_RETORN
    FROM DEPARTMENTS D RIGHT JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    WHERE EMPLOYEE_ID = P_ID;
  
  ELSE
  V_RETORN := 'ENTER AN ID BETWEEN 0 AND 999999';
  END IF;
  
  RETURN V_RETORN;

END;

-- INSIDE JAVA

DECLARE

  DEPARTMENT_NAME VARCHAR2(4000);

BEGIN
  DEPARTMENT_NAME:=FUNC_RETDEPT(100);
  DBMS_OUTPUT.PUT_LINE('DEPARTMENT NAME: ' || DEPARTMENT_NAME);
END;

