CREATE TABLE LOG_PERSONAGEM(
	ID_LOG NUMBER PRIMARY KEY,
	ID NUMBER NOT NULL,
	SALARIO_VELHO NUMBER(10,2) NOT NULL,
	SALARIO_NOVO NUMBER(10,2) NOT NULL,
	USUARIO VARCHAR2(30) NOT NULL,
	DATAHORA DATE NOT NULL,
		CONSTRAINT FK_PER_LOG FOREIGN KEY (ID) REFERENCES PERSONAGEM(ID)

);

CREATE SEQUENCE SEQ_UPD_PERSONAGEM
START WITH 4
INCREMENT BY 1
NOCACHE
NOCYCLE;