CREATE TABLE PERSONAGEM(
	ID NUMBER PRIMARY KEY NOT NULL,
	NOME VARCHAR2(120) NOT NULL,
	SALARIO NUMBER(10,2) NOT NULL
);

INSERT INTO PERSONAGEM(ID,NOME,SALARIO)
VALUES (SEQ_UPD_PERSONAGEM.NEXTVAL,'RAZIEL MIRANDA',	8600.76);
INSERT INTO PERSONAGEM(ID,NOME,SALARIO)
VALUES (SEQ_UPD_PERSONAGEM.NEXTVAL,'JAIARA MIRANDA',	8600.76);
INSERT INTO PERSONAGEM(ID,NOME,SALARIO)
VALUES (SEQ_UPD_PERSONAGEM.NEXTVAL,'NELIA MIRANDA',	8600.76);
