-- EX:0 RETORNAR NOME DO DEPARTAMENTO DO FUNCIONARIO (TURBINADO)
-- FRASE DE SELECT EX:0 --
    SELECT COUNT(*) INTO QTDE FROM EMPLOYEES WHERE EMPLOYEE_ID = P_ID;

        SELECT DEPARTMENT_NAME INTO RETORNO 
        FROM EMPLOYEES E
        LEFT JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        WHERE EMPLOYEE_ID = P_ID;
-- FRASE DE SELECT EX:0 --


CREATE OR REPLACE 
  
  FUNCTION FUNC_RET_NAME_DEPT (P_ID IN NUMBER)

RETURN VARCHAR2

IS

  RETORNO DEPARTMENTS.DEPARTMENT_NAME%TYPE;
  QTDE NUMBER(1);

BEGIN

  IF P_ID > 0 AND P_ID <= 999999 THEN

    SELECT COUNT(*) INTO QTDE FROM EMPLOYEES WHERE EMPLOYEE_ID = P_ID;

      IF QTDE = 1 THEN

        SELECT DEPARTMENT_NAME INTO RETORNO 
        FROM EMPLOYEES E
        LEFT JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        WHERE EMPLOYEE_ID = P_ID;
      ELSE
        RETORNO := 'NÃO HÁ FUNCIONARIO';
      
      END IF;
  
  ELSE
    RETORNO := 'ID FORA DA FAIXA';
  END IF;

  RETURN RETORNO;

END;

-- CHAMANDO FUNÇÃO NOME DO DEPARTAMENTO

DECLARE

  NAME_DEPT VARCHAR(4000);

BEGIN

  NAME_DEPT:=FUNC_RET_NAME_DEPT(10000000);
  
  DBMS_OUTPUT.PUT_LINE('DEPARTMENT NAME: ' || NAME_DEPT);

END;
-- EX:0 RETORNAR NOME DO DEPARTAMENTO DO FUNCIONARIO (TURBINADO)




-- FRASE DE SELECT EX:1 --
SELECT JOB_TITLE 
FROM JOBS J
INNER JOIN EMPLOYEES E
ON J.job_id = E.job_id
WHERE EMPLOYEE_ID = 102;
-- FRASE DE SELECT EX:1 --


-- EX1: MOSTRAR NOME DO CARGO DO FUNCIONARIO
CREATE OR REPLACE FUNCTION FUNC_NOM_JOB (P_ID IN NUMBER)

RETURN VARCHAR2

IS

  RETORNO JOBS.JOB_TITLE%TYPE;
  QTDE NUMBER(1)

BEGIN


  IF P_ID > 0 AND P_ID <= 999999 THEN

        IF QTDE = 1 THEN
          SELECT JOB_TITLE 
          FROM JOBS J
          INNER JOIN EMPLOYEES E
          ON J.job_id = E.job_id
          WHERE EMPLOYEE_ID = P_ID;
        ELSE
        RETORNO := 'NÃO HÁ FUNCIONARIO NESSE ID';
      END IF

  ELSE

    RETURNO := 'ID FORA DA FAIXA';

  END IF

  RETURN RETORNO;
END;
-- EX1: MOSTRAR NOME DO CARGO DO FUNCIONARIO




-- EX2: NOME DO PAIS QUE O FUNCIONARIO TRABALHA

-- FRASE DE SELECT EX:2 --
SELECT COUNTRY_NAME INTO RETORNO
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
LEFT JOIN COUNTRIES C ON C.COUNTRY_ID = L.COUNTRY_ID 
WHERE EMPLOYEE_ID = P_ID;

-- PROGRAMAÇÃO


-- PROGRAMAÇÃO


-- LEMBRETES:

-- COLUNA AMBIGUA TEM QUE DEFINIR QUAIS VOCE TA PUXANDO (PRECISO ESTUDAR ISSO)