CREATE OR REPLACE FUNCTION FUNC_DIVISAO(PDIVISOR IN NUMBER, PDIVIDENDO IN NUMBER)
RETURN NUMBER
IS
  VRETORNO NUMBER;
  VPARAMETROS VARCHAR2(4000); 
  VNUMERO_CODIGO NUMBER(6);
  VNOME_CODIGO VARCHAR2(4000);
  VNOME_PROC VARCHAR(30) := $$PLSQL_UNIT;
  VNUMLINHA NUMBER;
BEGIN
  VRETORNO := PDIVISOR / PDIVIDENDO;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
	VPARAMETROS := 'PDIVISOR: '||PDIVISOR||', PDIVIDENDO: '||PDIVIDENDO;
	VNUMERO_CODIGO := SQLCODE;
	VNOME_CODIGO := SQLERRM;
  VNUMLINHA := $$PLSQL_LINE;
    INSERT INTO LOG_ERRO_EXECUCAO(ID_LOG, NOME_CODIGO, PARAMETROS, NUMERO_ERRO, DESCRICAO_ERRO, NUMERO_LINHA, USUARIO, DATA, STATUS)
          VALUES(SEQ_LOG_PROGEXEC.NEXTVAL, VNOME_PROC,VPARAMETRO, VNUMERO_CODIGO, VNOME_CODIGO, VNUMLINHA, USER, SYSDATE, 'E');
    COMMIT;
    RETURN SQLCODE;
END;