CREATE OR REPLACE FUNCTION FUNC_AUMENTOSALPERSONAGEM(P_ID IN NUMBER, P_SAL IN NUMBER)
RETURN NUMBER

IS

VQTDE NUMBER(1);
RET NUMBER(3) := 0;
NOV_SAL PERSONAGE.SALARIO%TYPE;

BEGIN

IF P_SAL > 0 AND P_SAL < 99999999.99 THEN
  SELECT COUNT(*) INTO VQTDE FROM PERSONAGEM WHERE ID = P_ID;
  IF VQTDE = 1 THEN
    SELECT SALARIO INTO NOV_SAL FROM PERSONAGEM WHERE ID = P_ID;
    UPDATE PERSONAGEM SET SALARIO = P_SAL WHERE ID = P_ID;
    INSERT INTO LOG_PERSONAGEM(ID_LOG,ID,SALARIO_VELHO,SALARIO_NOVO,USUARIO,DATAHORAL)
    VALUES(SEQ_UPD_PERSONAGEM.NEXTVAL,P_ID,NOV_SAL,P_SAL,USER,SYSDATE);
  ELSE
  RET := -998;
  END IF;
ELSE

RET := -999;
END IF;

COMMIT;
RETURN RET;

END;