DECLARE
    X NUMBER;
BEGIN
    X:= FUNC_INS_PESSOA('Pedro silva', 1000.52);
    DBMS_OUTPUT.PUT_LINE('RESULTADO '|| X);
END;


  CREATE TABLE "HR"."PESSOA_LAS" 
   (	"ID" NUMBER(6,0), 
	"NOME" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	"SALARIO" NUMBER(10,2), 
	 CONSTRAINT "UQ_NOME_PESSOA" UNIQUE ("NOME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

create or replace 
FUNCTION FUNC_INS_PESSOA2(PID IN NUMBER, PNOME IN VARCHAR2, PSALARIO IN NUMBER)
RETURN NUMBER

IS 
  RETORNO NUMBER(3) :=0;
  VQTDE NUMBER(1);
  VID PESSOA_LAS.ID%TYPE;
  
BEGIN
SELECT COUNT(*) INTO VQTDE FROM PESSOA_LAS WHERE ID = PID;          
IF VQTDE = 1 THEN

  IF LENGTH(PNOME) <=120 THEN
      SELECT COUNT(*) INTO VQTDE FROM PESSOA_LAS                  
          WHERE TRANSLATE(UPPER(NOME),'ÃÁÀÂÄÉÈËÊÍÌÎÏÓÒÔÕÖÚÙÜÛÇÑ','AAAAAEEEEIIIIOOOOOUUUUCN') 
             = TRANSLATE(UPPER(PNOME),'ÃÁÀÂÄÉÈËÊÍÌÎÏÓÒÔÕÖÚÙÜÛÇÑ','AAAAAEEEEIIIIOOOOOUUUUCN');          
             
      IF VQTDE = 0 THEN
      
          IF (PSALARIO <= 99999999.99 AND PSALARIO >= 0) THEN
                UPDATE PESSOA_LAS SET ID = PID, SALARIO = PSALARIO, NOME = PNOME
                  WHERE ID = PID;
            COMMIT;
            
          
          ELSE
              RETORNO := -997; --MENOR QUE 0 OU MAIOR QUE O LIMITE--
          END IF;
        
      ELSE
          RETORNO := -998; --NOMES IGUAIS--
      END IF;
          
  ELSE
      RETORNO := -999; --NOME MAIOR DO QUE CABE NA COLUNA--
  END IF;
  
ELSE
    RETORNO := -996; -- NAO EXISTE
END IF;

  RETURN RETORNO;
END;