CREATE TABLE LOG_ERRO_EXECUCAO(
  ID_LOG NUMBER PRIMARY KEY,
  NOME_CODIGO VARCHAR2(30) NOT NULL,
  PARAMETROS VARCHAR(4000) NULL,
  NUMERO_ERRO VARCHAR2(30) NOT NULL,
  DESCRICAO_ERRO VARCHAR2(4000) NOT NULL,
  NUMERO_LINHA NUMBER NOT NULL,
  USUARIO VARCHAR2(30),
  DATA DATE NOT NULL,
  STATUS CHAR(1) NOT NULL,
  DESCRICAO_SOLUCAO VARCHAR2(4000),
  CONSTRAINT CK_STATUS_LOGPROGEXE CHECK (STATUS IN('E', 'R'))
  );
  
CREATE SEQUENCE SEQ_LOG_PROGEXEC
START WITH 1 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;