CREATE TABLE PERSONAGEM(
	ID NUMBER PRIMARY KEY NOT NULL,
	NOME VARCHAR2(120) NOT NULL,
	SALARIO NUMBER(10,2) NOT NULL
);

INSERT INTO PERSONAGEM(ID,NOME,SALARIO)
VALUES (SEQ_UPD_PERSONAGEM.NEXTVAL,'RAZIEL MIRANDA',	8600.76);
INSERT INTO PERSONAGEM(ID,NOME,SALARIO)
VALUES (SEQ_UPD_PERSONAGEM.NEXTVAL,'JAIARA MIRANDA',	8600.76);
INSERT INTO PERSONAGEM(ID,NOME,SALARIO)
VALUES (SEQ_UPD_PERSONAGEM.NEXTVAL,'NELIA MIRANDA',	8600.76);


CREATE TABLE LOG_PERSONAGEM(
	ID_LOG NUMBER PRIMARY KEY,
	ID NUMBER NOT NULL,
	SALARIO_VELHO NUMBER(10,2) NOT NULL,
	SALARIO_NOVO NUMBER(10,2) NOT NULL,
	USUARIO VARCHAR2(30) NOT NULL,
	DATAHORA DATE NOT NULL,
		CONSTRAINT FK_PER_LOG FOREIGN KEY (ID) REFERENCES PERSONAGEM(ID)

);
COMMIT;

SELECT * FROM PERSONAGEM;

CREATE SEQUENCE SEQ_UPD_PERSONAGEM
START WITH 4
INCREMENT BY 1
NOCACHE
NOCYCLE;